package com.yifeng.web.vo;

import java.util.List;
import java.util.Map;

import com.ds.fw.vo.BaseVO;

public class RelationVO extends BaseVO{
	 /**
     * serialVersionUID
     */
    private static final long serialVersionUID = 2285754085647216626L;
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.user_name
     *
     * @mbggenerated
     */
    private String userName;

	private String menuName;
	
	private String menuId;
	
	
	public String getMenuId() {
		return menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public String getMenuName() {
		return menuName;
	}

	public void setMenuName(String menuName) {
		this.menuName = menuName;
	}

	/**
	 * role
	 * */
	private List<Map<String, Object>> roleList;

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public List<Map<String, Object>> getRoleList() {
		return roleList;
	}

	public void setRoleList(List<Map<String, Object>> roleList) {
		this.roleList = roleList;
	}


}
