package com.yifeng.web.vo;

import java.util.Date;
import java.util.Set;

import com.ds.fw.vo.BaseVO;

public class RoleVo extends BaseVO implements Comparable<RoleVo>{
	
	
		/**
		 * serialVersionUID
		 */
		private static final long serialVersionUID = -7175641167202835838L;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to
		 * the database column t_role.id
		 *
		 * @mbggenerated
		 */
		private String id;
		private String text;
		private String state;

		public String getState() {
			return state;
		}

		public void setState(String state) {
			this.state = state;
		}




		private Set<RoleVo> children;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to
		 * the database column t_role.role_name
		 *
		 * @mbggenerated
		 */
		private String roleName;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to
		 * the database column t_role.group_id
		 *
		 * @mbggenerated
		 */
		private String groupId;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to
		 * the database column t_role.sortorder
		 *
		 * @mbggenerated
		 */
		private Short sortorder;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to
		 * the database column t_role.memo
		 *
		 * @mbggenerated
		 */
		private String memo;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to
		 * the database column t_role.delete
		 *
		 * @mbggenerated
		 */
		private String delete;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to
		 * the database column t_role.create_by
		 *
		 * @mbggenerated
		 */
		private String createBy;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to
		 * the database column t_role.create_time
		 *
		 * @mbggenerated
		 */
		private Date createTime;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to
		 * the database column t_role.update_by
		 *
		 * @mbggenerated
		 */
		private String updateBy;

		/**
		 * This field was generated by MyBatis Generator. This field corresponds to
		 * the database column t_role.update_time
		 *
		 * @mbggenerated
		 */
		private Date updateTime;

		/**
		 * This method was generated by MyBatis Generator. This method returns the
		 * value of the database column t_role.id
		 *
		 * @return the value of t_role.id
		 *
		 * @mbggenerated
		 */
	
		public String getId() {
			return id;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the
		 * value of the database column t_role.id
		 *
		 * @param id
		 *            the value for t_role.id
		 *
		 * @mbggenerated
		 */
		public void setId(String id) {
			this.id = id == null ? null : id.trim();
		}

		public String getText() {
			return text;
		}

		public void setText(String text) {
			this.text = text;
		}

		public Set<RoleVo> getChildren() {
			return children;
		}

		public void setChildren(Set<RoleVo> children) {
			this.children = children;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the
		 * value of the database column t_role.role_name
		 *
		 * @return the value of t_role.role_name
		 *
		 * @mbggenerated
		 */
		public String getRoleName() {
			return roleName;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the
		 * value of the database column t_role.role_name
		 *
		 * @param roleName
		 *            the value for t_role.role_name
		 *
		 * @mbggenerated
		 */
		public void setRoleName(String roleName) {
			this.roleName = roleName == null ? null : roleName.trim();
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the
		 * value of the database column t_role.group_id
		 *
		 * @return the value of t_role.group_id
		 *
		 * @mbggenerated
		 */
		public String getGroupId() {
			return groupId;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the
		 * value of the database column t_role.group_id
		 *
		 * @param groupId
		 *            the value for t_role.group_id
		 *
		 * @mbggenerated
		 */
		public void setGroupId(String groupId) {
			this.groupId = groupId == null ? null : groupId.trim();
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the
		 * value of the database column t_role.sortorder
		 *
		 * @return the value of t_role.sortorder
		 *
		 * @mbggenerated
		 */
		public Short getSortorder() {
			return sortorder;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the
		 * value of the database column t_role.sortorder
		 *
		 * @param sortorder
		 *            the value for t_role.sortorder
		 *
		 * @mbggenerated
		 */
		public void setSortorder(Short sortorder) {
			this.sortorder = sortorder;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the
		 * value of the database column t_role.memo
		 *
		 * @return the value of t_role.memo
		 *
		 * @mbggenerated
		 */
		public String getMemo() {
			return memo;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the
		 * value of the database column t_role.memo
		 *
		 * @param memo
		 *            the value for t_role.memo
		 *
		 * @mbggenerated
		 */
		public void setMemo(String memo) {
			this.memo = memo == null ? null : memo.trim();
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the
		 * value of the database column t_role.delete
		 *
		 * @return the value of t_role.delete
		 *
		 * @mbggenerated
		 */
		public String getDelete() {
			return delete;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the
		 * value of the database column t_role.delete
		 *
		 * @param delete
		 *            the value for t_role.delete
		 *
		 * @mbggenerated
		 */
		public void setDelete(String delete) {
			this.delete = delete == null ? null : delete.trim();
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the
		 * value of the database column t_role.create_by
		 *
		 * @return the value of t_role.create_by
		 *
		 * @mbggenerated
		 */
		public String getCreateBy() {
			return createBy;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the
		 * value of the database column t_role.create_by
		 *
		 * @param createBy
		 *            the value for t_role.create_by
		 *
		 * @mbggenerated
		 */
		public void setCreateBy(String createBy) {
			this.createBy = createBy == null ? null : createBy.trim();
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the
		 * value of the database column t_role.create_time
		 *
		 * @return the value of t_role.create_time
		 *
		 * @mbggenerated
		 */
		public Date getCreateTime() {
			return createTime;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the
		 * value of the database column t_role.create_time
		 *
		 * @param createTime
		 *            the value for t_role.create_time
		 *
		 * @mbggenerated
		 */
		public void setCreateTime(Date createTime) {
			this.createTime = createTime;
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the
		 * value of the database column t_role.update_by
		 *
		 * @return the value of t_role.update_by
		 *
		 * @mbggenerated
		 */
		public String getUpdateBy() {
			return updateBy;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the
		 * value of the database column t_role.update_by
		 *
		 * @param updateBy
		 *            the value for t_role.update_by
		 *
		 * @mbggenerated
		 */
		public void setUpdateBy(String updateBy) {
			this.updateBy = updateBy == null ? null : updateBy.trim();
		}

		/**
		 * This method was generated by MyBatis Generator. This method returns the
		 * value of the database column t_role.update_time
		 *
		 * @return the value of t_role.update_time
		 *
		 * @mbggenerated
		 */
		public Date getUpdateTime() {
			return updateTime;
		}

		/**
		 * This method was generated by MyBatis Generator. This method sets the
		 * value of the database column t_role.update_time
		 *
		 * @param updateTime
		 *            the value for t_role.update_time
		 *
		 * @mbggenerated
		 */
		public void setUpdateTime(Date updateTime) {
			this.updateTime = updateTime;
		}




	@Override
	public int compareTo(RoleVo o) {
		if(o.getSortorder() > this.getSortorder()){
            return -1;
        }else{
            return 1;
        }
	}

}
