package com.ifeng.entitys;

import java.util.Date;

public class CtmFabric {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.id
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.name
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.category
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.code
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String code;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.material_code
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String materialCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.image_url
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String imageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.composition
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String composition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.lining
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String lining;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.tidying
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String tidying;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.qian_tiao
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String qianTiao;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.color
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String color;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.extend_info
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String extendInfo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.create_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column cmt_fabric.update_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.id
	 * @return  the value of cmt_fabric.id
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.id
	 * @param id  the value for cmt_fabric.id
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.name
	 * @return  the value of cmt_fabric.name
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.name
	 * @param name  the value for cmt_fabric.name
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.category
	 * @return  the value of cmt_fabric.category
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.category
	 * @param category  the value for cmt_fabric.category
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.code
	 * @return  the value of cmt_fabric.code
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getCode() {
		return code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.code
	 * @param code  the value for cmt_fabric.code
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setCode(String code) {
		this.code = code;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.material_code
	 * @return  the value of cmt_fabric.material_code
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getMaterialCode() {
		return materialCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.material_code
	 * @param materialCode  the value for cmt_fabric.material_code
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setMaterialCode(String materialCode) {
		this.materialCode = materialCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.image_url
	 * @return  the value of cmt_fabric.image_url
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.image_url
	 * @param imageUrl  the value for cmt_fabric.image_url
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.composition
	 * @return  the value of cmt_fabric.composition
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getComposition() {
		return composition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.composition
	 * @param composition  the value for cmt_fabric.composition
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setComposition(String composition) {
		this.composition = composition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.lining
	 * @return  the value of cmt_fabric.lining
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getLining() {
		return lining;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.lining
	 * @param lining  the value for cmt_fabric.lining
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setLining(String lining) {
		this.lining = lining;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.tidying
	 * @return  the value of cmt_fabric.tidying
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getTidying() {
		return tidying;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.tidying
	 * @param tidying  the value for cmt_fabric.tidying
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setTidying(String tidying) {
		this.tidying = tidying;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.qian_tiao
	 * @return  the value of cmt_fabric.qian_tiao
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getQianTiao() {
		return qianTiao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.qian_tiao
	 * @param qianTiao  the value for cmt_fabric.qian_tiao
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setQianTiao(String qianTiao) {
		this.qianTiao = qianTiao;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.color
	 * @return  the value of cmt_fabric.color
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getColor() {
		return color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.color
	 * @param color  the value for cmt_fabric.color
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setColor(String color) {
		this.color = color;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.extend_info
	 * @return  the value of cmt_fabric.extend_info
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getExtendInfo() {
		return extendInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.extend_info
	 * @param extendInfo  the value for cmt_fabric.extend_info
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setExtendInfo(String extendInfo) {
		this.extendInfo = extendInfo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.create_time
	 * @return  the value of cmt_fabric.create_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.create_time
	 * @param createTime  the value for cmt_fabric.create_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column cmt_fabric.update_time
	 * @return  the value of cmt_fabric.update_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column cmt_fabric.update_time
	 * @param updateTime  the value for cmt_fabric.update_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}