package com.ifeng.entitys;

import java.util.Date;

public class CtmOrder {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.order_sn
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String orderSn;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.user_id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.user_name
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String userName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.money
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Integer money;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.pay_money
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Integer payMoney;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.pay_type
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Integer payType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.pay_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Date payTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.order_status
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Byte orderStatus;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.delivery_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String deliveryTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.carriage
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Integer carriage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.invoice_type
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Byte invoiceType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.reservation_no
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String reservationNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.ip
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String ip;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.create_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.update_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_order.pay_sn
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String paySn;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.id
	 * @return  the value of ctm_order.id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.id
	 * @param id  the value for ctm_order.id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.order_sn
	 * @return  the value of ctm_order.order_sn
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getOrderSn() {
		return orderSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.order_sn
	 * @param orderSn  the value for ctm_order.order_sn
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setOrderSn(String orderSn) {
		this.orderSn = orderSn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.user_id
	 * @return  the value of ctm_order.user_id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.user_id
	 * @param userId  the value for ctm_order.user_id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.user_name
	 * @return  the value of ctm_order.user_name
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getUserName() {
		return userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.user_name
	 * @param userName  the value for ctm_order.user_name
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setUserName(String userName) {
		this.userName = userName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.money
	 * @return  the value of ctm_order.money
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Integer getMoney() {
		return money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.money
	 * @param money  the value for ctm_order.money
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setMoney(Integer money) {
		this.money = money;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.pay_money
	 * @return  the value of ctm_order.pay_money
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Integer getPayMoney() {
		return payMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.pay_money
	 * @param payMoney  the value for ctm_order.pay_money
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setPayMoney(Integer payMoney) {
		this.payMoney = payMoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.pay_type
	 * @return  the value of ctm_order.pay_type
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Integer getPayType() {
		return payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.pay_type
	 * @param payType  the value for ctm_order.pay_type
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setPayType(Integer payType) {
		this.payType = payType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.pay_time
	 * @return  the value of ctm_order.pay_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Date getPayTime() {
		return payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.pay_time
	 * @param payTime  the value for ctm_order.pay_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setPayTime(Date payTime) {
		this.payTime = payTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.order_status
	 * @return  the value of ctm_order.order_status
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Byte getOrderStatus() {
		return orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.order_status
	 * @param orderStatus  the value for ctm_order.order_status
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setOrderStatus(Byte orderStatus) {
		this.orderStatus = orderStatus;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.delivery_time
	 * @return  the value of ctm_order.delivery_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getDeliveryTime() {
		return deliveryTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.delivery_time
	 * @param deliveryTime  the value for ctm_order.delivery_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setDeliveryTime(String deliveryTime) {
		this.deliveryTime = deliveryTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.carriage
	 * @return  the value of ctm_order.carriage
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Integer getCarriage() {
		return carriage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.carriage
	 * @param carriage  the value for ctm_order.carriage
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setCarriage(Integer carriage) {
		this.carriage = carriage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.invoice_type
	 * @return  the value of ctm_order.invoice_type
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Byte getInvoiceType() {
		return invoiceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.invoice_type
	 * @param invoiceType  the value for ctm_order.invoice_type
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setInvoiceType(Byte invoiceType) {
		this.invoiceType = invoiceType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.reservation_no
	 * @return  the value of ctm_order.reservation_no
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getReservationNo() {
		return reservationNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.reservation_no
	 * @param reservationNo  the value for ctm_order.reservation_no
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setReservationNo(String reservationNo) {
		this.reservationNo = reservationNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.ip
	 * @return  the value of ctm_order.ip
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.ip
	 * @param ip  the value for ctm_order.ip
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.create_time
	 * @return  the value of ctm_order.create_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.create_time
	 * @param createTime  the value for ctm_order.create_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.update_time
	 * @return  the value of ctm_order.update_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.update_time
	 * @param updateTime  the value for ctm_order.update_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_order.pay_sn
	 * @return  the value of ctm_order.pay_sn
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getPaySn() {
		return paySn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_order.pay_sn
	 * @param paySn  the value for ctm_order.pay_sn
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setPaySn(String paySn) {
		this.paySn = paySn;
	}
}