package com.ifeng.entitys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CtmOrderExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public CtmOrderExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andOrderSnIsNull() {
			addCriterion("order_sn is null");
			return (Criteria) this;
		}

		public Criteria andOrderSnIsNotNull() {
			addCriterion("order_sn is not null");
			return (Criteria) this;
		}

		public Criteria andOrderSnEqualTo(String value) {
			addCriterion("order_sn =", value, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnNotEqualTo(String value) {
			addCriterion("order_sn <>", value, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnGreaterThan(String value) {
			addCriterion("order_sn >", value, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnGreaterThanOrEqualTo(String value) {
			addCriterion("order_sn >=", value, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnLessThan(String value) {
			addCriterion("order_sn <", value, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnLessThanOrEqualTo(String value) {
			addCriterion("order_sn <=", value, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnLike(String value) {
			addCriterion("order_sn like", value, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnNotLike(String value) {
			addCriterion("order_sn not like", value, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnIn(List<String> values) {
			addCriterion("order_sn in", values, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnNotIn(List<String> values) {
			addCriterion("order_sn not in", values, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnBetween(String value1, String value2) {
			addCriterion("order_sn between", value1, value2, "orderSn");
			return (Criteria) this;
		}

		public Criteria andOrderSnNotBetween(String value1, String value2) {
			addCriterion("order_sn not between", value1, value2, "orderSn");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNull() {
			addCriterion("user_name is null");
			return (Criteria) this;
		}

		public Criteria andUserNameIsNotNull() {
			addCriterion("user_name is not null");
			return (Criteria) this;
		}

		public Criteria andUserNameEqualTo(String value) {
			addCriterion("user_name =", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotEqualTo(String value) {
			addCriterion("user_name <>", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThan(String value) {
			addCriterion("user_name >", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameGreaterThanOrEqualTo(String value) {
			addCriterion("user_name >=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThan(String value) {
			addCriterion("user_name <", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLessThanOrEqualTo(String value) {
			addCriterion("user_name <=", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameLike(String value) {
			addCriterion("user_name like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotLike(String value) {
			addCriterion("user_name not like", value, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameIn(List<String> values) {
			addCriterion("user_name in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotIn(List<String> values) {
			addCriterion("user_name not in", values, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameBetween(String value1, String value2) {
			addCriterion("user_name between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andUserNameNotBetween(String value1, String value2) {
			addCriterion("user_name not between", value1, value2, "userName");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNull() {
			addCriterion("money is null");
			return (Criteria) this;
		}

		public Criteria andMoneyIsNotNull() {
			addCriterion("money is not null");
			return (Criteria) this;
		}

		public Criteria andMoneyEqualTo(Integer value) {
			addCriterion("money =", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotEqualTo(Integer value) {
			addCriterion("money <>", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThan(Integer value) {
			addCriterion("money >", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyGreaterThanOrEqualTo(Integer value) {
			addCriterion("money >=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThan(Integer value) {
			addCriterion("money <", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyLessThanOrEqualTo(Integer value) {
			addCriterion("money <=", value, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyIn(List<Integer> values) {
			addCriterion("money in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotIn(List<Integer> values) {
			addCriterion("money not in", values, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyBetween(Integer value1, Integer value2) {
			addCriterion("money between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andMoneyNotBetween(Integer value1, Integer value2) {
			addCriterion("money not between", value1, value2, "money");
			return (Criteria) this;
		}

		public Criteria andPayMoneyIsNull() {
			addCriterion("pay_money is null");
			return (Criteria) this;
		}

		public Criteria andPayMoneyIsNotNull() {
			addCriterion("pay_money is not null");
			return (Criteria) this;
		}

		public Criteria andPayMoneyEqualTo(Integer value) {
			addCriterion("pay_money =", value, "payMoney");
			return (Criteria) this;
		}

		public Criteria andPayMoneyNotEqualTo(Integer value) {
			addCriterion("pay_money <>", value, "payMoney");
			return (Criteria) this;
		}

		public Criteria andPayMoneyGreaterThan(Integer value) {
			addCriterion("pay_money >", value, "payMoney");
			return (Criteria) this;
		}

		public Criteria andPayMoneyGreaterThanOrEqualTo(Integer value) {
			addCriterion("pay_money >=", value, "payMoney");
			return (Criteria) this;
		}

		public Criteria andPayMoneyLessThan(Integer value) {
			addCriterion("pay_money <", value, "payMoney");
			return (Criteria) this;
		}

		public Criteria andPayMoneyLessThanOrEqualTo(Integer value) {
			addCriterion("pay_money <=", value, "payMoney");
			return (Criteria) this;
		}

		public Criteria andPayMoneyIn(List<Integer> values) {
			addCriterion("pay_money in", values, "payMoney");
			return (Criteria) this;
		}

		public Criteria andPayMoneyNotIn(List<Integer> values) {
			addCriterion("pay_money not in", values, "payMoney");
			return (Criteria) this;
		}

		public Criteria andPayMoneyBetween(Integer value1, Integer value2) {
			addCriterion("pay_money between", value1, value2, "payMoney");
			return (Criteria) this;
		}

		public Criteria andPayMoneyNotBetween(Integer value1, Integer value2) {
			addCriterion("pay_money not between", value1, value2, "payMoney");
			return (Criteria) this;
		}

		public Criteria andPayTypeIsNull() {
			addCriterion("pay_type is null");
			return (Criteria) this;
		}

		public Criteria andPayTypeIsNotNull() {
			addCriterion("pay_type is not null");
			return (Criteria) this;
		}

		public Criteria andPayTypeEqualTo(Integer value) {
			addCriterion("pay_type =", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotEqualTo(Integer value) {
			addCriterion("pay_type <>", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeGreaterThan(Integer value) {
			addCriterion("pay_type >", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("pay_type >=", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeLessThan(Integer value) {
			addCriterion("pay_type <", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeLessThanOrEqualTo(Integer value) {
			addCriterion("pay_type <=", value, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeIn(List<Integer> values) {
			addCriterion("pay_type in", values, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotIn(List<Integer> values) {
			addCriterion("pay_type not in", values, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeBetween(Integer value1, Integer value2) {
			addCriterion("pay_type between", value1, value2, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("pay_type not between", value1, value2, "payType");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNull() {
			addCriterion("pay_time is null");
			return (Criteria) this;
		}

		public Criteria andPayTimeIsNotNull() {
			addCriterion("pay_time is not null");
			return (Criteria) this;
		}

		public Criteria andPayTimeEqualTo(Date value) {
			addCriterion("pay_time =", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotEqualTo(Date value) {
			addCriterion("pay_time <>", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThan(Date value) {
			addCriterion("pay_time >", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("pay_time >=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThan(Date value) {
			addCriterion("pay_time <", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeLessThanOrEqualTo(Date value) {
			addCriterion("pay_time <=", value, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeIn(List<Date> values) {
			addCriterion("pay_time in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotIn(List<Date> values) {
			addCriterion("pay_time not in", values, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeBetween(Date value1, Date value2) {
			addCriterion("pay_time between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andPayTimeNotBetween(Date value1, Date value2) {
			addCriterion("pay_time not between", value1, value2, "payTime");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNull() {
			addCriterion("order_status is null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIsNotNull() {
			addCriterion("order_status is not null");
			return (Criteria) this;
		}

		public Criteria andOrderStatusEqualTo(Byte value) {
			addCriterion("order_status =", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotEqualTo(Byte value) {
			addCriterion("order_status <>", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThan(Byte value) {
			addCriterion("order_status >", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("order_status >=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThan(Byte value) {
			addCriterion("order_status <", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusLessThanOrEqualTo(Byte value) {
			addCriterion("order_status <=", value, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusIn(List<Byte> values) {
			addCriterion("order_status in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotIn(List<Byte> values) {
			addCriterion("order_status not in", values, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusBetween(Byte value1, Byte value2) {
			addCriterion("order_status between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andOrderStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("order_status not between", value1, value2, "orderStatus");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeIsNull() {
			addCriterion("delivery_time is null");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeIsNotNull() {
			addCriterion("delivery_time is not null");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeEqualTo(String value) {
			addCriterion("delivery_time =", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeNotEqualTo(String value) {
			addCriterion("delivery_time <>", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeGreaterThan(String value) {
			addCriterion("delivery_time >", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeGreaterThanOrEqualTo(String value) {
			addCriterion("delivery_time >=", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeLessThan(String value) {
			addCriterion("delivery_time <", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeLessThanOrEqualTo(String value) {
			addCriterion("delivery_time <=", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeLike(String value) {
			addCriterion("delivery_time like", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeNotLike(String value) {
			addCriterion("delivery_time not like", value, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeIn(List<String> values) {
			addCriterion("delivery_time in", values, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeNotIn(List<String> values) {
			addCriterion("delivery_time not in", values, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeBetween(String value1, String value2) {
			addCriterion("delivery_time between", value1, value2, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andDeliveryTimeNotBetween(String value1, String value2) {
			addCriterion("delivery_time not between", value1, value2, "deliveryTime");
			return (Criteria) this;
		}

		public Criteria andCarriageIsNull() {
			addCriterion("carriage is null");
			return (Criteria) this;
		}

		public Criteria andCarriageIsNotNull() {
			addCriterion("carriage is not null");
			return (Criteria) this;
		}

		public Criteria andCarriageEqualTo(Integer value) {
			addCriterion("carriage =", value, "carriage");
			return (Criteria) this;
		}

		public Criteria andCarriageNotEqualTo(Integer value) {
			addCriterion("carriage <>", value, "carriage");
			return (Criteria) this;
		}

		public Criteria andCarriageGreaterThan(Integer value) {
			addCriterion("carriage >", value, "carriage");
			return (Criteria) this;
		}

		public Criteria andCarriageGreaterThanOrEqualTo(Integer value) {
			addCriterion("carriage >=", value, "carriage");
			return (Criteria) this;
		}

		public Criteria andCarriageLessThan(Integer value) {
			addCriterion("carriage <", value, "carriage");
			return (Criteria) this;
		}

		public Criteria andCarriageLessThanOrEqualTo(Integer value) {
			addCriterion("carriage <=", value, "carriage");
			return (Criteria) this;
		}

		public Criteria andCarriageIn(List<Integer> values) {
			addCriterion("carriage in", values, "carriage");
			return (Criteria) this;
		}

		public Criteria andCarriageNotIn(List<Integer> values) {
			addCriterion("carriage not in", values, "carriage");
			return (Criteria) this;
		}

		public Criteria andCarriageBetween(Integer value1, Integer value2) {
			addCriterion("carriage between", value1, value2, "carriage");
			return (Criteria) this;
		}

		public Criteria andCarriageNotBetween(Integer value1, Integer value2) {
			addCriterion("carriage not between", value1, value2, "carriage");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeIsNull() {
			addCriterion("invoice_type is null");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeIsNotNull() {
			addCriterion("invoice_type is not null");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeEqualTo(Byte value) {
			addCriterion("invoice_type =", value, "invoiceType");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeNotEqualTo(Byte value) {
			addCriterion("invoice_type <>", value, "invoiceType");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeGreaterThan(Byte value) {
			addCriterion("invoice_type >", value, "invoiceType");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("invoice_type >=", value, "invoiceType");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeLessThan(Byte value) {
			addCriterion("invoice_type <", value, "invoiceType");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeLessThanOrEqualTo(Byte value) {
			addCriterion("invoice_type <=", value, "invoiceType");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeIn(List<Byte> values) {
			addCriterion("invoice_type in", values, "invoiceType");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeNotIn(List<Byte> values) {
			addCriterion("invoice_type not in", values, "invoiceType");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeBetween(Byte value1, Byte value2) {
			addCriterion("invoice_type between", value1, value2, "invoiceType");
			return (Criteria) this;
		}

		public Criteria andInvoiceTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("invoice_type not between", value1, value2, "invoiceType");
			return (Criteria) this;
		}

		public Criteria andReservationNoIsNull() {
			addCriterion("reservation_no is null");
			return (Criteria) this;
		}

		public Criteria andReservationNoIsNotNull() {
			addCriterion("reservation_no is not null");
			return (Criteria) this;
		}

		public Criteria andReservationNoEqualTo(String value) {
			addCriterion("reservation_no =", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoNotEqualTo(String value) {
			addCriterion("reservation_no <>", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoGreaterThan(String value) {
			addCriterion("reservation_no >", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoGreaterThanOrEqualTo(String value) {
			addCriterion("reservation_no >=", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoLessThan(String value) {
			addCriterion("reservation_no <", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoLessThanOrEqualTo(String value) {
			addCriterion("reservation_no <=", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoLike(String value) {
			addCriterion("reservation_no like", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoNotLike(String value) {
			addCriterion("reservation_no not like", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoIn(List<String> values) {
			addCriterion("reservation_no in", values, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoNotIn(List<String> values) {
			addCriterion("reservation_no not in", values, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoBetween(String value1, String value2) {
			addCriterion("reservation_no between", value1, value2, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoNotBetween(String value1, String value2) {
			addCriterion("reservation_no not between", value1, value2, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andIpIsNull() {
			addCriterion("ip is null");
			return (Criteria) this;
		}

		public Criteria andIpIsNotNull() {
			addCriterion("ip is not null");
			return (Criteria) this;
		}

		public Criteria andIpEqualTo(String value) {
			addCriterion("ip =", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotEqualTo(String value) {
			addCriterion("ip <>", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThan(String value) {
			addCriterion("ip >", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpGreaterThanOrEqualTo(String value) {
			addCriterion("ip >=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThan(String value) {
			addCriterion("ip <", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLessThanOrEqualTo(String value) {
			addCriterion("ip <=", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpLike(String value) {
			addCriterion("ip like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotLike(String value) {
			addCriterion("ip not like", value, "ip");
			return (Criteria) this;
		}

		public Criteria andIpIn(List<String> values) {
			addCriterion("ip in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotIn(List<String> values) {
			addCriterion("ip not in", values, "ip");
			return (Criteria) this;
		}

		public Criteria andIpBetween(String value1, String value2) {
			addCriterion("ip between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andIpNotBetween(String value1, String value2) {
			addCriterion("ip not between", value1, value2, "ip");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andPaySnIsNull() {
			addCriterion("pay_sn is null");
			return (Criteria) this;
		}

		public Criteria andPaySnIsNotNull() {
			addCriterion("pay_sn is not null");
			return (Criteria) this;
		}

		public Criteria andPaySnEqualTo(String value) {
			addCriterion("pay_sn =", value, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnNotEqualTo(String value) {
			addCriterion("pay_sn <>", value, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnGreaterThan(String value) {
			addCriterion("pay_sn >", value, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnGreaterThanOrEqualTo(String value) {
			addCriterion("pay_sn >=", value, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnLessThan(String value) {
			addCriterion("pay_sn <", value, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnLessThanOrEqualTo(String value) {
			addCriterion("pay_sn <=", value, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnLike(String value) {
			addCriterion("pay_sn like", value, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnNotLike(String value) {
			addCriterion("pay_sn not like", value, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnIn(List<String> values) {
			addCriterion("pay_sn in", values, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnNotIn(List<String> values) {
			addCriterion("pay_sn not in", values, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnBetween(String value1, String value2) {
			addCriterion("pay_sn between", value1, value2, "paySn");
			return (Criteria) this;
		}

		public Criteria andPaySnNotBetween(String value1, String value2) {
			addCriterion("pay_sn not between", value1, value2, "paySn");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctm_order
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 10 08:57:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}