package com.ifeng.entitys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CtmProductExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public CtmProductExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNull() {
			addCriterion("brand_name is null");
			return (Criteria) this;
		}

		public Criteria andBrandNameIsNotNull() {
			addCriterion("brand_name is not null");
			return (Criteria) this;
		}

		public Criteria andBrandNameEqualTo(String value) {
			addCriterion("brand_name =", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotEqualTo(String value) {
			addCriterion("brand_name <>", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThan(String value) {
			addCriterion("brand_name >", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
			addCriterion("brand_name >=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThan(String value) {
			addCriterion("brand_name <", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLessThanOrEqualTo(String value) {
			addCriterion("brand_name <=", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameLike(String value) {
			addCriterion("brand_name like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotLike(String value) {
			addCriterion("brand_name not like", value, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameIn(List<String> values) {
			addCriterion("brand_name in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotIn(List<String> values) {
			addCriterion("brand_name not in", values, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameBetween(String value1, String value2) {
			addCriterion("brand_name between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andBrandNameNotBetween(String value1, String value2) {
			addCriterion("brand_name not between", value1, value2, "brandName");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Integer value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Integer value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Integer value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Integer value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Integer value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Integer> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Integer> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Integer value1, Integer value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Integer value1, Integer value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andImageUrlIsNull() {
			addCriterion("image_url is null");
			return (Criteria) this;
		}

		public Criteria andImageUrlIsNotNull() {
			addCriterion("image_url is not null");
			return (Criteria) this;
		}

		public Criteria andImageUrlEqualTo(String value) {
			addCriterion("image_url =", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotEqualTo(String value) {
			addCriterion("image_url <>", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlGreaterThan(String value) {
			addCriterion("image_url >", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
			addCriterion("image_url >=", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlLessThan(String value) {
			addCriterion("image_url <", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlLessThanOrEqualTo(String value) {
			addCriterion("image_url <=", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlLike(String value) {
			addCriterion("image_url like", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotLike(String value) {
			addCriterion("image_url not like", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlIn(List<String> values) {
			addCriterion("image_url in", values, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotIn(List<String> values) {
			addCriterion("image_url not in", values, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlBetween(String value1, String value2) {
			addCriterion("image_url between", value1, value2, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotBetween(String value1, String value2) {
			addCriterion("image_url not between", value1, value2, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andSubImagesIsNull() {
			addCriterion("sub_images is null");
			return (Criteria) this;
		}

		public Criteria andSubImagesIsNotNull() {
			addCriterion("sub_images is not null");
			return (Criteria) this;
		}

		public Criteria andSubImagesEqualTo(String value) {
			addCriterion("sub_images =", value, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesNotEqualTo(String value) {
			addCriterion("sub_images <>", value, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesGreaterThan(String value) {
			addCriterion("sub_images >", value, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesGreaterThanOrEqualTo(String value) {
			addCriterion("sub_images >=", value, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesLessThan(String value) {
			addCriterion("sub_images <", value, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesLessThanOrEqualTo(String value) {
			addCriterion("sub_images <=", value, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesLike(String value) {
			addCriterion("sub_images like", value, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesNotLike(String value) {
			addCriterion("sub_images not like", value, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesIn(List<String> values) {
			addCriterion("sub_images in", values, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesNotIn(List<String> values) {
			addCriterion("sub_images not in", values, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesBetween(String value1, String value2) {
			addCriterion("sub_images between", value1, value2, "subImages");
			return (Criteria) this;
		}

		public Criteria andSubImagesNotBetween(String value1, String value2) {
			addCriterion("sub_images not between", value1, value2, "subImages");
			return (Criteria) this;
		}

		public Criteria andDetailImageIsNull() {
			addCriterion("detail_image is null");
			return (Criteria) this;
		}

		public Criteria andDetailImageIsNotNull() {
			addCriterion("detail_image is not null");
			return (Criteria) this;
		}

		public Criteria andDetailImageEqualTo(String value) {
			addCriterion("detail_image =", value, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageNotEqualTo(String value) {
			addCriterion("detail_image <>", value, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageGreaterThan(String value) {
			addCriterion("detail_image >", value, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageGreaterThanOrEqualTo(String value) {
			addCriterion("detail_image >=", value, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageLessThan(String value) {
			addCriterion("detail_image <", value, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageLessThanOrEqualTo(String value) {
			addCriterion("detail_image <=", value, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageLike(String value) {
			addCriterion("detail_image like", value, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageNotLike(String value) {
			addCriterion("detail_image not like", value, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageIn(List<String> values) {
			addCriterion("detail_image in", values, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageNotIn(List<String> values) {
			addCriterion("detail_image not in", values, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageBetween(String value1, String value2) {
			addCriterion("detail_image between", value1, value2, "detailImage");
			return (Criteria) this;
		}

		public Criteria andDetailImageNotBetween(String value1, String value2) {
			addCriterion("detail_image not between", value1, value2, "detailImage");
			return (Criteria) this;
		}

		public Criteria andAdImageIsNull() {
			addCriterion("ad_image is null");
			return (Criteria) this;
		}

		public Criteria andAdImageIsNotNull() {
			addCriterion("ad_image is not null");
			return (Criteria) this;
		}

		public Criteria andAdImageEqualTo(String value) {
			addCriterion("ad_image =", value, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageNotEqualTo(String value) {
			addCriterion("ad_image <>", value, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageGreaterThan(String value) {
			addCriterion("ad_image >", value, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageGreaterThanOrEqualTo(String value) {
			addCriterion("ad_image >=", value, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageLessThan(String value) {
			addCriterion("ad_image <", value, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageLessThanOrEqualTo(String value) {
			addCriterion("ad_image <=", value, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageLike(String value) {
			addCriterion("ad_image like", value, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageNotLike(String value) {
			addCriterion("ad_image not like", value, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageIn(List<String> values) {
			addCriterion("ad_image in", values, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageNotIn(List<String> values) {
			addCriterion("ad_image not in", values, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageBetween(String value1, String value2) {
			addCriterion("ad_image between", value1, value2, "adImage");
			return (Criteria) this;
		}

		public Criteria andAdImageNotBetween(String value1, String value2) {
			addCriterion("ad_image not between", value1, value2, "adImage");
			return (Criteria) this;
		}

		public Criteria andVipPriceIsNull() {
			addCriterion("vip_price is null");
			return (Criteria) this;
		}

		public Criteria andVipPriceIsNotNull() {
			addCriterion("vip_price is not null");
			return (Criteria) this;
		}

		public Criteria andVipPriceEqualTo(Integer value) {
			addCriterion("vip_price =", value, "vipPrice");
			return (Criteria) this;
		}

		public Criteria andVipPriceNotEqualTo(Integer value) {
			addCriterion("vip_price <>", value, "vipPrice");
			return (Criteria) this;
		}

		public Criteria andVipPriceGreaterThan(Integer value) {
			addCriterion("vip_price >", value, "vipPrice");
			return (Criteria) this;
		}

		public Criteria andVipPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("vip_price >=", value, "vipPrice");
			return (Criteria) this;
		}

		public Criteria andVipPriceLessThan(Integer value) {
			addCriterion("vip_price <", value, "vipPrice");
			return (Criteria) this;
		}

		public Criteria andVipPriceLessThanOrEqualTo(Integer value) {
			addCriterion("vip_price <=", value, "vipPrice");
			return (Criteria) this;
		}

		public Criteria andVipPriceIn(List<Integer> values) {
			addCriterion("vip_price in", values, "vipPrice");
			return (Criteria) this;
		}

		public Criteria andVipPriceNotIn(List<Integer> values) {
			addCriterion("vip_price not in", values, "vipPrice");
			return (Criteria) this;
		}

		public Criteria andVipPriceBetween(Integer value1, Integer value2) {
			addCriterion("vip_price between", value1, value2, "vipPrice");
			return (Criteria) this;
		}

		public Criteria andVipPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("vip_price not between", value1, value2, "vipPrice");
			return (Criteria) this;
		}

		public Criteria andMarketPriceIsNull() {
			addCriterion("market_price is null");
			return (Criteria) this;
		}

		public Criteria andMarketPriceIsNotNull() {
			addCriterion("market_price is not null");
			return (Criteria) this;
		}

		public Criteria andMarketPriceEqualTo(Integer value) {
			addCriterion("market_price =", value, "marketPrice");
			return (Criteria) this;
		}

		public Criteria andMarketPriceNotEqualTo(Integer value) {
			addCriterion("market_price <>", value, "marketPrice");
			return (Criteria) this;
		}

		public Criteria andMarketPriceGreaterThan(Integer value) {
			addCriterion("market_price >", value, "marketPrice");
			return (Criteria) this;
		}

		public Criteria andMarketPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("market_price >=", value, "marketPrice");
			return (Criteria) this;
		}

		public Criteria andMarketPriceLessThan(Integer value) {
			addCriterion("market_price <", value, "marketPrice");
			return (Criteria) this;
		}

		public Criteria andMarketPriceLessThanOrEqualTo(Integer value) {
			addCriterion("market_price <=", value, "marketPrice");
			return (Criteria) this;
		}

		public Criteria andMarketPriceIn(List<Integer> values) {
			addCriterion("market_price in", values, "marketPrice");
			return (Criteria) this;
		}

		public Criteria andMarketPriceNotIn(List<Integer> values) {
			addCriterion("market_price not in", values, "marketPrice");
			return (Criteria) this;
		}

		public Criteria andMarketPriceBetween(Integer value1, Integer value2) {
			addCriterion("market_price between", value1, value2, "marketPrice");
			return (Criteria) this;
		}

		public Criteria andMarketPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("market_price not between", value1, value2, "marketPrice");
			return (Criteria) this;
		}

		public Criteria andSubTitleIsNull() {
			addCriterion("sub_title is null");
			return (Criteria) this;
		}

		public Criteria andSubTitleIsNotNull() {
			addCriterion("sub_title is not null");
			return (Criteria) this;
		}

		public Criteria andSubTitleEqualTo(String value) {
			addCriterion("sub_title =", value, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleNotEqualTo(String value) {
			addCriterion("sub_title <>", value, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleGreaterThan(String value) {
			addCriterion("sub_title >", value, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleGreaterThanOrEqualTo(String value) {
			addCriterion("sub_title >=", value, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleLessThan(String value) {
			addCriterion("sub_title <", value, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleLessThanOrEqualTo(String value) {
			addCriterion("sub_title <=", value, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleLike(String value) {
			addCriterion("sub_title like", value, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleNotLike(String value) {
			addCriterion("sub_title not like", value, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleIn(List<String> values) {
			addCriterion("sub_title in", values, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleNotIn(List<String> values) {
			addCriterion("sub_title not in", values, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleBetween(String value1, String value2) {
			addCriterion("sub_title between", value1, value2, "subTitle");
			return (Criteria) this;
		}

		public Criteria andSubTitleNotBetween(String value1, String value2) {
			addCriterion("sub_title not between", value1, value2, "subTitle");
			return (Criteria) this;
		}

		public Criteria andCategoryIsNull() {
			addCriterion("category is null");
			return (Criteria) this;
		}

		public Criteria andCategoryIsNotNull() {
			addCriterion("category is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryEqualTo(String value) {
			addCriterion("category =", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotEqualTo(String value) {
			addCriterion("category <>", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryGreaterThan(String value) {
			addCriterion("category >", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryGreaterThanOrEqualTo(String value) {
			addCriterion("category >=", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLessThan(String value) {
			addCriterion("category <", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLessThanOrEqualTo(String value) {
			addCriterion("category <=", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLike(String value) {
			addCriterion("category like", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotLike(String value) {
			addCriterion("category not like", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryIn(List<String> values) {
			addCriterion("category in", values, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotIn(List<String> values) {
			addCriterion("category not in", values, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryBetween(String value1, String value2) {
			addCriterion("category between", value1, value2, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotBetween(String value1, String value2) {
			addCriterion("category not between", value1, value2, "category");
			return (Criteria) this;
		}

		public Criteria andCtmPropsIsNull() {
			addCriterion("ctm_props is null");
			return (Criteria) this;
		}

		public Criteria andCtmPropsIsNotNull() {
			addCriterion("ctm_props is not null");
			return (Criteria) this;
		}

		public Criteria andCtmPropsEqualTo(String value) {
			addCriterion("ctm_props =", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsNotEqualTo(String value) {
			addCriterion("ctm_props <>", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsGreaterThan(String value) {
			addCriterion("ctm_props >", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsGreaterThanOrEqualTo(String value) {
			addCriterion("ctm_props >=", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsLessThan(String value) {
			addCriterion("ctm_props <", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsLessThanOrEqualTo(String value) {
			addCriterion("ctm_props <=", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsLike(String value) {
			addCriterion("ctm_props like", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsNotLike(String value) {
			addCriterion("ctm_props not like", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsIn(List<String> values) {
			addCriterion("ctm_props in", values, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsNotIn(List<String> values) {
			addCriterion("ctm_props not in", values, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsBetween(String value1, String value2) {
			addCriterion("ctm_props between", value1, value2, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsNotBetween(String value1, String value2) {
			addCriterion("ctm_props not between", value1, value2, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andFabricIdIsNull() {
			addCriterion("fabric_id is null");
			return (Criteria) this;
		}

		public Criteria andFabricIdIsNotNull() {
			addCriterion("fabric_id is not null");
			return (Criteria) this;
		}

		public Criteria andFabricIdEqualTo(Long value) {
			addCriterion("fabric_id =", value, "fabricId");
			return (Criteria) this;
		}

		public Criteria andFabricIdNotEqualTo(Long value) {
			addCriterion("fabric_id <>", value, "fabricId");
			return (Criteria) this;
		}

		public Criteria andFabricIdGreaterThan(Long value) {
			addCriterion("fabric_id >", value, "fabricId");
			return (Criteria) this;
		}

		public Criteria andFabricIdGreaterThanOrEqualTo(Long value) {
			addCriterion("fabric_id >=", value, "fabricId");
			return (Criteria) this;
		}

		public Criteria andFabricIdLessThan(Long value) {
			addCriterion("fabric_id <", value, "fabricId");
			return (Criteria) this;
		}

		public Criteria andFabricIdLessThanOrEqualTo(Long value) {
			addCriterion("fabric_id <=", value, "fabricId");
			return (Criteria) this;
		}

		public Criteria andFabricIdIn(List<Long> values) {
			addCriterion("fabric_id in", values, "fabricId");
			return (Criteria) this;
		}

		public Criteria andFabricIdNotIn(List<Long> values) {
			addCriterion("fabric_id not in", values, "fabricId");
			return (Criteria) this;
		}

		public Criteria andFabricIdBetween(Long value1, Long value2) {
			addCriterion("fabric_id between", value1, value2, "fabricId");
			return (Criteria) this;
		}

		public Criteria andFabricIdNotBetween(Long value1, Long value2) {
			addCriterion("fabric_id not between", value1, value2, "fabricId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ctm_product
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctm_product
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 08 12:11:09 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}