package com.ifeng.entitys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CtmReservationExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public CtmReservationExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andReservationNoIsNull() {
			addCriterion("reservation_no is null");
			return (Criteria) this;
		}

		public Criteria andReservationNoIsNotNull() {
			addCriterion("reservation_no is not null");
			return (Criteria) this;
		}

		public Criteria andReservationNoEqualTo(String value) {
			addCriterion("reservation_no =", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoNotEqualTo(String value) {
			addCriterion("reservation_no <>", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoGreaterThan(String value) {
			addCriterion("reservation_no >", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoGreaterThanOrEqualTo(String value) {
			addCriterion("reservation_no >=", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoLessThan(String value) {
			addCriterion("reservation_no <", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoLessThanOrEqualTo(String value) {
			addCriterion("reservation_no <=", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoLike(String value) {
			addCriterion("reservation_no like", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoNotLike(String value) {
			addCriterion("reservation_no not like", value, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoIn(List<String> values) {
			addCriterion("reservation_no in", values, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoNotIn(List<String> values) {
			addCriterion("reservation_no not in", values, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoBetween(String value1, String value2) {
			addCriterion("reservation_no between", value1, value2, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andReservationNoNotBetween(String value1, String value2) {
			addCriterion("reservation_no not between", value1, value2, "reservationNo");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNull() {
			addCriterion("user_id is null");
			return (Criteria) this;
		}

		public Criteria andUserIdIsNotNull() {
			addCriterion("user_id is not null");
			return (Criteria) this;
		}

		public Criteria andUserIdEqualTo(Long value) {
			addCriterion("user_id =", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotEqualTo(Long value) {
			addCriterion("user_id <>", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThan(Long value) {
			addCriterion("user_id >", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdGreaterThanOrEqualTo(Long value) {
			addCriterion("user_id >=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThan(Long value) {
			addCriterion("user_id <", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdLessThanOrEqualTo(Long value) {
			addCriterion("user_id <=", value, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdIn(List<Long> values) {
			addCriterion("user_id in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotIn(List<Long> values) {
			addCriterion("user_id not in", values, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdBetween(Long value1, Long value2) {
			addCriterion("user_id between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUserIdNotBetween(Long value1, Long value2) {
			addCriterion("user_id not between", value1, value2, "userId");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNull() {
			addCriterion("username is null");
			return (Criteria) this;
		}

		public Criteria andUsernameIsNotNull() {
			addCriterion("username is not null");
			return (Criteria) this;
		}

		public Criteria andUsernameEqualTo(String value) {
			addCriterion("username =", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotEqualTo(String value) {
			addCriterion("username <>", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThan(String value) {
			addCriterion("username >", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameGreaterThanOrEqualTo(String value) {
			addCriterion("username >=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThan(String value) {
			addCriterion("username <", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLessThanOrEqualTo(String value) {
			addCriterion("username <=", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameLike(String value) {
			addCriterion("username like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotLike(String value) {
			addCriterion("username not like", value, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameIn(List<String> values) {
			addCriterion("username in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotIn(List<String> values) {
			addCriterion("username not in", values, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameBetween(String value1, String value2) {
			addCriterion("username between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andUsernameNotBetween(String value1, String value2) {
			addCriterion("username not between", value1, value2, "username");
			return (Criteria) this;
		}

		public Criteria andGenderIsNull() {
			addCriterion("gender is null");
			return (Criteria) this;
		}

		public Criteria andGenderIsNotNull() {
			addCriterion("gender is not null");
			return (Criteria) this;
		}

		public Criteria andGenderEqualTo(Byte value) {
			addCriterion("gender =", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotEqualTo(Byte value) {
			addCriterion("gender <>", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThan(Byte value) {
			addCriterion("gender >", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderGreaterThanOrEqualTo(Byte value) {
			addCriterion("gender >=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThan(Byte value) {
			addCriterion("gender <", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderLessThanOrEqualTo(Byte value) {
			addCriterion("gender <=", value, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderIn(List<Byte> values) {
			addCriterion("gender in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotIn(List<Byte> values) {
			addCriterion("gender not in", values, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderBetween(Byte value1, Byte value2) {
			addCriterion("gender between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andGenderNotBetween(Byte value1, Byte value2) {
			addCriterion("gender not between", value1, value2, "gender");
			return (Criteria) this;
		}

		public Criteria andAddressIsNull() {
			addCriterion("address is null");
			return (Criteria) this;
		}

		public Criteria andAddressIsNotNull() {
			addCriterion("address is not null");
			return (Criteria) this;
		}

		public Criteria andAddressEqualTo(String value) {
			addCriterion("address =", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotEqualTo(String value) {
			addCriterion("address <>", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThan(String value) {
			addCriterion("address >", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressGreaterThanOrEqualTo(String value) {
			addCriterion("address >=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThan(String value) {
			addCriterion("address <", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLessThanOrEqualTo(String value) {
			addCriterion("address <=", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressLike(String value) {
			addCriterion("address like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotLike(String value) {
			addCriterion("address not like", value, "address");
			return (Criteria) this;
		}

		public Criteria andAddressIn(List<String> values) {
			addCriterion("address in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotIn(List<String> values) {
			addCriterion("address not in", values, "address");
			return (Criteria) this;
		}

		public Criteria andAddressBetween(String value1, String value2) {
			addCriterion("address between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andAddressNotBetween(String value1, String value2) {
			addCriterion("address not between", value1, value2, "address");
			return (Criteria) this;
		}

		public Criteria andProvinceIsNull() {
			addCriterion("province is null");
			return (Criteria) this;
		}

		public Criteria andProvinceIsNotNull() {
			addCriterion("province is not null");
			return (Criteria) this;
		}

		public Criteria andProvinceEqualTo(String value) {
			addCriterion("province =", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotEqualTo(String value) {
			addCriterion("province <>", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceGreaterThan(String value) {
			addCriterion("province >", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceGreaterThanOrEqualTo(String value) {
			addCriterion("province >=", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLessThan(String value) {
			addCriterion("province <", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLessThanOrEqualTo(String value) {
			addCriterion("province <=", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceLike(String value) {
			addCriterion("province like", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotLike(String value) {
			addCriterion("province not like", value, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceIn(List<String> values) {
			addCriterion("province in", values, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotIn(List<String> values) {
			addCriterion("province not in", values, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceBetween(String value1, String value2) {
			addCriterion("province between", value1, value2, "province");
			return (Criteria) this;
		}

		public Criteria andProvinceNotBetween(String value1, String value2) {
			addCriterion("province not between", value1, value2, "province");
			return (Criteria) this;
		}

		public Criteria andCityIsNull() {
			addCriterion("city is null");
			return (Criteria) this;
		}

		public Criteria andCityIsNotNull() {
			addCriterion("city is not null");
			return (Criteria) this;
		}

		public Criteria andCityEqualTo(String value) {
			addCriterion("city =", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotEqualTo(String value) {
			addCriterion("city <>", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThan(String value) {
			addCriterion("city >", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityGreaterThanOrEqualTo(String value) {
			addCriterion("city >=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThan(String value) {
			addCriterion("city <", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLessThanOrEqualTo(String value) {
			addCriterion("city <=", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityLike(String value) {
			addCriterion("city like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotLike(String value) {
			addCriterion("city not like", value, "city");
			return (Criteria) this;
		}

		public Criteria andCityIn(List<String> values) {
			addCriterion("city in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotIn(List<String> values) {
			addCriterion("city not in", values, "city");
			return (Criteria) this;
		}

		public Criteria andCityBetween(String value1, String value2) {
			addCriterion("city between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andCityNotBetween(String value1, String value2) {
			addCriterion("city not between", value1, value2, "city");
			return (Criteria) this;
		}

		public Criteria andDistrictIsNull() {
			addCriterion("district is null");
			return (Criteria) this;
		}

		public Criteria andDistrictIsNotNull() {
			addCriterion("district is not null");
			return (Criteria) this;
		}

		public Criteria andDistrictEqualTo(String value) {
			addCriterion("district =", value, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictNotEqualTo(String value) {
			addCriterion("district <>", value, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictGreaterThan(String value) {
			addCriterion("district >", value, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictGreaterThanOrEqualTo(String value) {
			addCriterion("district >=", value, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictLessThan(String value) {
			addCriterion("district <", value, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictLessThanOrEqualTo(String value) {
			addCriterion("district <=", value, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictLike(String value) {
			addCriterion("district like", value, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictNotLike(String value) {
			addCriterion("district not like", value, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictIn(List<String> values) {
			addCriterion("district in", values, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictNotIn(List<String> values) {
			addCriterion("district not in", values, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictBetween(String value1, String value2) {
			addCriterion("district between", value1, value2, "district");
			return (Criteria) this;
		}

		public Criteria andDistrictNotBetween(String value1, String value2) {
			addCriterion("district not between", value1, value2, "district");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneIsNull() {
			addCriterion("mobile_phone is null");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneIsNotNull() {
			addCriterion("mobile_phone is not null");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneEqualTo(String value) {
			addCriterion("mobile_phone =", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotEqualTo(String value) {
			addCriterion("mobile_phone <>", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneGreaterThan(String value) {
			addCriterion("mobile_phone >", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneGreaterThanOrEqualTo(String value) {
			addCriterion("mobile_phone >=", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneLessThan(String value) {
			addCriterion("mobile_phone <", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneLessThanOrEqualTo(String value) {
			addCriterion("mobile_phone <=", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneLike(String value) {
			addCriterion("mobile_phone like", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotLike(String value) {
			addCriterion("mobile_phone not like", value, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneIn(List<String> values) {
			addCriterion("mobile_phone in", values, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotIn(List<String> values) {
			addCriterion("mobile_phone not in", values, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneBetween(String value1, String value2) {
			addCriterion("mobile_phone between", value1, value2, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andMobilePhoneNotBetween(String value1, String value2) {
			addCriterion("mobile_phone not between", value1, value2, "mobilePhone");
			return (Criteria) this;
		}

		public Criteria andBookTimeIsNull() {
			addCriterion("book_time is null");
			return (Criteria) this;
		}

		public Criteria andBookTimeIsNotNull() {
			addCriterion("book_time is not null");
			return (Criteria) this;
		}

		public Criteria andBookTimeEqualTo(Date value) {
			addCriterion("book_time =", value, "bookTime");
			return (Criteria) this;
		}

		public Criteria andBookTimeNotEqualTo(Date value) {
			addCriterion("book_time <>", value, "bookTime");
			return (Criteria) this;
		}

		public Criteria andBookTimeGreaterThan(Date value) {
			addCriterion("book_time >", value, "bookTime");
			return (Criteria) this;
		}

		public Criteria andBookTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("book_time >=", value, "bookTime");
			return (Criteria) this;
		}

		public Criteria andBookTimeLessThan(Date value) {
			addCriterion("book_time <", value, "bookTime");
			return (Criteria) this;
		}

		public Criteria andBookTimeLessThanOrEqualTo(Date value) {
			addCriterion("book_time <=", value, "bookTime");
			return (Criteria) this;
		}

		public Criteria andBookTimeIn(List<Date> values) {
			addCriterion("book_time in", values, "bookTime");
			return (Criteria) this;
		}

		public Criteria andBookTimeNotIn(List<Date> values) {
			addCriterion("book_time not in", values, "bookTime");
			return (Criteria) this;
		}

		public Criteria andBookTimeBetween(Date value1, Date value2) {
			addCriterion("book_time between", value1, value2, "bookTime");
			return (Criteria) this;
		}

		public Criteria andBookTimeNotBetween(Date value1, Date value2) {
			addCriterion("book_time not between", value1, value2, "bookTime");
			return (Criteria) this;
		}

		public Criteria andTailorNoIsNull() {
			addCriterion("tailor_no is null");
			return (Criteria) this;
		}

		public Criteria andTailorNoIsNotNull() {
			addCriterion("tailor_no is not null");
			return (Criteria) this;
		}

		public Criteria andTailorNoEqualTo(String value) {
			addCriterion("tailor_no =", value, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoNotEqualTo(String value) {
			addCriterion("tailor_no <>", value, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoGreaterThan(String value) {
			addCriterion("tailor_no >", value, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoGreaterThanOrEqualTo(String value) {
			addCriterion("tailor_no >=", value, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoLessThan(String value) {
			addCriterion("tailor_no <", value, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoLessThanOrEqualTo(String value) {
			addCriterion("tailor_no <=", value, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoLike(String value) {
			addCriterion("tailor_no like", value, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoNotLike(String value) {
			addCriterion("tailor_no not like", value, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoIn(List<String> values) {
			addCriterion("tailor_no in", values, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoNotIn(List<String> values) {
			addCriterion("tailor_no not in", values, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoBetween(String value1, String value2) {
			addCriterion("tailor_no between", value1, value2, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andTailorNoNotBetween(String value1, String value2) {
			addCriterion("tailor_no not between", value1, value2, "tailorNo");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(Byte value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(Byte value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(Byte value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(Byte value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(Byte value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(Byte value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<Byte> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<Byte> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(Byte value1, Byte value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(Byte value1, Byte value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andCtmPropsIsNull() {
			addCriterion("ctm_props is null");
			return (Criteria) this;
		}

		public Criteria andCtmPropsIsNotNull() {
			addCriterion("ctm_props is not null");
			return (Criteria) this;
		}

		public Criteria andCtmPropsEqualTo(String value) {
			addCriterion("ctm_props =", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsNotEqualTo(String value) {
			addCriterion("ctm_props <>", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsGreaterThan(String value) {
			addCriterion("ctm_props >", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsGreaterThanOrEqualTo(String value) {
			addCriterion("ctm_props >=", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsLessThan(String value) {
			addCriterion("ctm_props <", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsLessThanOrEqualTo(String value) {
			addCriterion("ctm_props <=", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsLike(String value) {
			addCriterion("ctm_props like", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsNotLike(String value) {
			addCriterion("ctm_props not like", value, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsIn(List<String> values) {
			addCriterion("ctm_props in", values, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsNotIn(List<String> values) {
			addCriterion("ctm_props not in", values, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsBetween(String value1, String value2) {
			addCriterion("ctm_props between", value1, value2, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andCtmPropsNotBetween(String value1, String value2) {
			addCriterion("ctm_props not between", value1, value2, "ctmProps");
			return (Criteria) this;
		}

		public Criteria andSkuIdIsNull() {
			addCriterion("sku_id is null");
			return (Criteria) this;
		}

		public Criteria andSkuIdIsNotNull() {
			addCriterion("sku_id is not null");
			return (Criteria) this;
		}

		public Criteria andSkuIdEqualTo(Long value) {
			addCriterion("sku_id =", value, "skuId");
			return (Criteria) this;
		}

		public Criteria andSkuIdNotEqualTo(Long value) {
			addCriterion("sku_id <>", value, "skuId");
			return (Criteria) this;
		}

		public Criteria andSkuIdGreaterThan(Long value) {
			addCriterion("sku_id >", value, "skuId");
			return (Criteria) this;
		}

		public Criteria andSkuIdGreaterThanOrEqualTo(Long value) {
			addCriterion("sku_id >=", value, "skuId");
			return (Criteria) this;
		}

		public Criteria andSkuIdLessThan(Long value) {
			addCriterion("sku_id <", value, "skuId");
			return (Criteria) this;
		}

		public Criteria andSkuIdLessThanOrEqualTo(Long value) {
			addCriterion("sku_id <=", value, "skuId");
			return (Criteria) this;
		}

		public Criteria andSkuIdIn(List<Long> values) {
			addCriterion("sku_id in", values, "skuId");
			return (Criteria) this;
		}

		public Criteria andSkuIdNotIn(List<Long> values) {
			addCriterion("sku_id not in", values, "skuId");
			return (Criteria) this;
		}

		public Criteria andSkuIdBetween(Long value1, Long value2) {
			addCriterion("sku_id between", value1, value2, "skuId");
			return (Criteria) this;
		}

		public Criteria andSkuIdNotBetween(Long value1, Long value2) {
			addCriterion("sku_id not between", value1, value2, "skuId");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andReservationTypeIsNull() {
			addCriterion("reservation_type is null");
			return (Criteria) this;
		}

		public Criteria andReservationTypeIsNotNull() {
			addCriterion("reservation_type is not null");
			return (Criteria) this;
		}

		public Criteria andReservationTypeEqualTo(Byte value) {
			addCriterion("reservation_type =", value, "reservationType");
			return (Criteria) this;
		}

		public Criteria andReservationTypeNotEqualTo(Byte value) {
			addCriterion("reservation_type <>", value, "reservationType");
			return (Criteria) this;
		}

		public Criteria andReservationTypeGreaterThan(Byte value) {
			addCriterion("reservation_type >", value, "reservationType");
			return (Criteria) this;
		}

		public Criteria andReservationTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("reservation_type >=", value, "reservationType");
			return (Criteria) this;
		}

		public Criteria andReservationTypeLessThan(Byte value) {
			addCriterion("reservation_type <", value, "reservationType");
			return (Criteria) this;
		}

		public Criteria andReservationTypeLessThanOrEqualTo(Byte value) {
			addCriterion("reservation_type <=", value, "reservationType");
			return (Criteria) this;
		}

		public Criteria andReservationTypeIn(List<Byte> values) {
			addCriterion("reservation_type in", values, "reservationType");
			return (Criteria) this;
		}

		public Criteria andReservationTypeNotIn(List<Byte> values) {
			addCriterion("reservation_type not in", values, "reservationType");
			return (Criteria) this;
		}

		public Criteria andReservationTypeBetween(Byte value1, Byte value2) {
			addCriterion("reservation_type between", value1, value2, "reservationType");
			return (Criteria) this;
		}

		public Criteria andReservationTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("reservation_type not between", value1, value2, "reservationType");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNull() {
			addCriterion("remark is null");
			return (Criteria) this;
		}

		public Criteria andRemarkIsNotNull() {
			addCriterion("remark is not null");
			return (Criteria) this;
		}

		public Criteria andRemarkEqualTo(String value) {
			addCriterion("remark =", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotEqualTo(String value) {
			addCriterion("remark <>", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThan(String value) {
			addCriterion("remark >", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkGreaterThanOrEqualTo(String value) {
			addCriterion("remark >=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThan(String value) {
			addCriterion("remark <", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLessThanOrEqualTo(String value) {
			addCriterion("remark <=", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkLike(String value) {
			addCriterion("remark like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotLike(String value) {
			addCriterion("remark not like", value, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkIn(List<String> values) {
			addCriterion("remark in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotIn(List<String> values) {
			addCriterion("remark not in", values, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkBetween(String value1, String value2) {
			addCriterion("remark between", value1, value2, "remark");
			return (Criteria) this;
		}

		public Criteria andRemarkNotBetween(String value1, String value2) {
			addCriterion("remark not between", value1, value2, "remark");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ctm_reservation
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 10 08:57:10 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}