package com.ifeng.entitys;

import java.util.Date;

public class CtmReservation {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.reservation_no
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String reservationNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.user_id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Long userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.username
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.gender
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Byte gender;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.address
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.province
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.city
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.district
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String district;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.mobile_phone
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String mobilePhone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.book_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Date bookTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.tailor_no
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String tailorNo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.status
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.ctm_props
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String ctmProps;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.sku_id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Long skuId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.create_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.update_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Date updateTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.reservation_type
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Byte reservationType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_reservation.remark
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String remark;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.id
	 * @return  the value of ctm_reservation.id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.id
	 * @param id  the value for ctm_reservation.id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.reservation_no
	 * @return  the value of ctm_reservation.reservation_no
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getReservationNo() {
		return reservationNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.reservation_no
	 * @param reservationNo  the value for ctm_reservation.reservation_no
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setReservationNo(String reservationNo) {
		this.reservationNo = reservationNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.user_id
	 * @return  the value of ctm_reservation.user_id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Long getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.user_id
	 * @param userId  the value for ctm_reservation.user_id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setUserId(Long userId) {
		this.userId = userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.username
	 * @return  the value of ctm_reservation.username
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.username
	 * @param username  the value for ctm_reservation.username
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.gender
	 * @return  the value of ctm_reservation.gender
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Byte getGender() {
		return gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.gender
	 * @param gender  the value for ctm_reservation.gender
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setGender(Byte gender) {
		this.gender = gender;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.address
	 * @return  the value of ctm_reservation.address
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.address
	 * @param address  the value for ctm_reservation.address
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.province
	 * @return  the value of ctm_reservation.province
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.province
	 * @param province  the value for ctm_reservation.province
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setProvince(String province) {
		this.province = province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.city
	 * @return  the value of ctm_reservation.city
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.city
	 * @param city  the value for ctm_reservation.city
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setCity(String city) {
		this.city = city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.district
	 * @return  the value of ctm_reservation.district
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getDistrict() {
		return district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.district
	 * @param district  the value for ctm_reservation.district
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setDistrict(String district) {
		this.district = district;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.mobile_phone
	 * @return  the value of ctm_reservation.mobile_phone
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getMobilePhone() {
		return mobilePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.mobile_phone
	 * @param mobilePhone  the value for ctm_reservation.mobile_phone
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setMobilePhone(String mobilePhone) {
		this.mobilePhone = mobilePhone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.book_time
	 * @return  the value of ctm_reservation.book_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Date getBookTime() {
		return bookTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.book_time
	 * @param bookTime  the value for ctm_reservation.book_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setBookTime(Date bookTime) {
		this.bookTime = bookTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.tailor_no
	 * @return  the value of ctm_reservation.tailor_no
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getTailorNo() {
		return tailorNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.tailor_no
	 * @param tailorNo  the value for ctm_reservation.tailor_no
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setTailorNo(String tailorNo) {
		this.tailorNo = tailorNo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.status
	 * @return  the value of ctm_reservation.status
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.status
	 * @param status  the value for ctm_reservation.status
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.ctm_props
	 * @return  the value of ctm_reservation.ctm_props
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getCtmProps() {
		return ctmProps;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.ctm_props
	 * @param ctmProps  the value for ctm_reservation.ctm_props
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setCtmProps(String ctmProps) {
		this.ctmProps = ctmProps;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.sku_id
	 * @return  the value of ctm_reservation.sku_id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Long getSkuId() {
		return skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.sku_id
	 * @param skuId  the value for ctm_reservation.sku_id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setSkuId(Long skuId) {
		this.skuId = skuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.create_time
	 * @return  the value of ctm_reservation.create_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.create_time
	 * @param createTime  the value for ctm_reservation.create_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.update_time
	 * @return  the value of ctm_reservation.update_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.update_time
	 * @param updateTime  the value for ctm_reservation.update_time
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.reservation_type
	 * @return  the value of ctm_reservation.reservation_type
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Byte getReservationType() {
		return reservationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.reservation_type
	 * @param reservationType  the value for ctm_reservation.reservation_type
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setReservationType(Byte reservationType) {
		this.reservationType = reservationType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_reservation.remark
	 * @return  the value of ctm_reservation.remark
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_reservation.remark
	 * @param remark  the value for ctm_reservation.remark
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}
}