package com.ifeng.entitys;

public class CtmUser {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_user.id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_user.username
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_user.sex
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_user.phone
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private Long phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_user.address
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_user.password
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	private String password;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_user.id
	 * @return  the value of ctm_user.id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_user.id
	 * @param id  the value for ctm_user.id
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_user.username
	 * @return  the value of ctm_user.username
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_user.username
	 * @param username  the value for ctm_user.username
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_user.sex
	 * @return  the value of ctm_user.sex
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_user.sex
	 * @param sex  the value for ctm_user.sex
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setSex(String sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_user.phone
	 * @return  the value of ctm_user.phone
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public Long getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_user.phone
	 * @param phone  the value for ctm_user.phone
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setPhone(Long phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_user.address
	 * @return  the value of ctm_user.address
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_user.address
	 * @param address  the value for ctm_user.address
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_user.password
	 * @return  the value of ctm_user.password
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_user.password
	 * @param password  the value for ctm_user.password
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}
}