package com.ifeng.entitys;

import java.util.Date;

public class DmsDocument {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_document.id
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_document.document_sn
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    private String documentSn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_document.author_name
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    private String authorName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_document.create_time
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_document.update_time
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_document.document_name
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    private String documentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_document.remark
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_document.headimgsrc
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    private String headimgsrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_document.filesrc
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    private String filesrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_document.context
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_document.id
     *
     * @return the value of dms_document.id
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_document.id
     *
     * @param id the value for dms_document.id
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_document.document_sn
     *
     * @return the value of dms_document.document_sn
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public String getDocumentSn() {
        return documentSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_document.document_sn
     *
     * @param documentSn the value for dms_document.document_sn
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public void setDocumentSn(String documentSn) {
        this.documentSn = documentSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_document.author_name
     *
     * @return the value of dms_document.author_name
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public String getAuthorName() {
        return authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_document.author_name
     *
     * @param authorName the value for dms_document.author_name
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_document.create_time
     *
     * @return the value of dms_document.create_time
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_document.create_time
     *
     * @param createTime the value for dms_document.create_time
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_document.update_time
     *
     * @return the value of dms_document.update_time
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_document.update_time
     *
     * @param updateTime the value for dms_document.update_time
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_document.document_name
     *
     * @return the value of dms_document.document_name
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public String getDocumentName() {
        return documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_document.document_name
     *
     * @param documentName the value for dms_document.document_name
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public void setDocumentName(String documentName) {
        this.documentName = documentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_document.remark
     *
     * @return the value of dms_document.remark
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_document.remark
     *
     * @param remark the value for dms_document.remark
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_document.headimgsrc
     *
     * @return the value of dms_document.headimgsrc
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public String getHeadimgsrc() {
        return headimgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_document.headimgsrc
     *
     * @param headimgsrc the value for dms_document.headimgsrc
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public void setHeadimgsrc(String headimgsrc) {
        this.headimgsrc = headimgsrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_document.filesrc
     *
     * @return the value of dms_document.filesrc
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public String getFilesrc() {
        return filesrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_document.filesrc
     *
     * @param filesrc the value for dms_document.filesrc
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public void setFilesrc(String filesrc) {
        this.filesrc = filesrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_document.context
     *
     * @return the value of dms_document.context
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_document.context
     *
     * @param context the value for dms_document.context
     *
     * @mbg.generated Wed Jan 17 11:21:59 CST 2018
     */
    public void setContext(String context) {
        this.context = context;
    }
}