package com.ifeng.entitys;

public class DmsUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_user.id
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_user.username
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_user.sex
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_user.phone
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    private Long phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_user.address
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dms_user.password
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_user.id
     *
     * @return the value of dms_user.id
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_user.id
     *
     * @param id the value for dms_user.id
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_user.username
     *
     * @return the value of dms_user.username
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_user.username
     *
     * @param username the value for dms_user.username
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_user.sex
     *
     * @return the value of dms_user.sex
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_user.sex
     *
     * @param sex the value for dms_user.sex
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_user.phone
     *
     * @return the value of dms_user.phone
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public Long getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_user.phone
     *
     * @param phone the value for dms_user.phone
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public void setPhone(Long phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_user.address
     *
     * @return the value of dms_user.address
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_user.address
     *
     * @param address the value for dms_user.address
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dms_user.password
     *
     * @return the value of dms_user.password
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dms_user.password
     *
     * @param password the value for dms_user.password
     *
     * @mbg.generated Fri Jan 12 11:24:47 CST 2018
     */
    public void setPassword(String password) {
        this.password = password;
    }
}