package com.ifeng.mappers;

import com.ifeng.entitys.CtmOrder;
import com.ifeng.entitys.CtmOrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtmOrderMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	long countByExample(CtmOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int deleteByExample(CtmOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int insert(CtmOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int insertSelective(CtmOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	List<CtmOrder> selectByExample(CtmOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	CtmOrder selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CtmOrder record, @Param("example") CtmOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByExample(@Param("record") CtmOrder record, @Param("example") CtmOrderExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByPrimaryKeySelective(CtmOrder record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_order
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByPrimaryKey(CtmOrder record);
}