package com.ifeng.mappers;

import com.ifeng.entitys.CtmProduct;
import com.ifeng.entitys.CtmProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtmProductMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	long countByExample(CtmProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	int deleteByExample(CtmProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	int insert(CtmProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	int insertSelective(CtmProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	List<CtmProduct> selectByExample(CtmProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	CtmProduct selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CtmProduct record, @Param("example") CtmProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	int updateByExample(@Param("record") CtmProduct record, @Param("example") CtmProductExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	int updateByPrimaryKeySelective(CtmProduct record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_product
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	int updateByPrimaryKey(CtmProduct record);
}