package com.ifeng.mappers;

import com.ifeng.entitys.CtmReservation;
import com.ifeng.entitys.CtmReservationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtmReservationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	long countByExample(CtmReservationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int deleteByExample(CtmReservationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int insert(CtmReservation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int insertSelective(CtmReservation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	List<CtmReservation> selectByExample(CtmReservationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	CtmReservation selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CtmReservation record,
			@Param("example") CtmReservationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByExample(@Param("record") CtmReservation record, @Param("example") CtmReservationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByPrimaryKeySelective(CtmReservation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_reservation
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByPrimaryKey(CtmReservation record);
}