package com.ifeng.mappers;

import com.ifeng.entitys.CtmUser;
import com.ifeng.entitys.CtmUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CtmUserMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	long countByExample(CtmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int deleteByExample(CtmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int insert(CtmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int insertSelective(CtmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	List<CtmUser> selectByExample(CtmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	CtmUser selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByExampleSelective(@Param("record") CtmUser record, @Param("example") CtmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByExample(@Param("record") CtmUser record, @Param("example") CtmUserExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByPrimaryKeySelective(CtmUser record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table ctm_user
	 * @mbg.generated  Thu Jan 11 14:49:48 CST 2018
	 */
	int updateByPrimaryKey(CtmUser record);
}