package com.ifeng.entitys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CtmFabricExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public CtmFabricExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andCategoryIsNull() {
			addCriterion("category is null");
			return (Criteria) this;
		}

		public Criteria andCategoryIsNotNull() {
			addCriterion("category is not null");
			return (Criteria) this;
		}

		public Criteria andCategoryEqualTo(String value) {
			addCriterion("category =", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotEqualTo(String value) {
			addCriterion("category <>", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryGreaterThan(String value) {
			addCriterion("category >", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryGreaterThanOrEqualTo(String value) {
			addCriterion("category >=", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLessThan(String value) {
			addCriterion("category <", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLessThanOrEqualTo(String value) {
			addCriterion("category <=", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryLike(String value) {
			addCriterion("category like", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotLike(String value) {
			addCriterion("category not like", value, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryIn(List<String> values) {
			addCriterion("category in", values, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotIn(List<String> values) {
			addCriterion("category not in", values, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryBetween(String value1, String value2) {
			addCriterion("category between", value1, value2, "category");
			return (Criteria) this;
		}

		public Criteria andCategoryNotBetween(String value1, String value2) {
			addCriterion("category not between", value1, value2, "category");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeIsNull() {
			addCriterion("material_code is null");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeIsNotNull() {
			addCriterion("material_code is not null");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeEqualTo(String value) {
			addCriterion("material_code =", value, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeNotEqualTo(String value) {
			addCriterion("material_code <>", value, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeGreaterThan(String value) {
			addCriterion("material_code >", value, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeGreaterThanOrEqualTo(String value) {
			addCriterion("material_code >=", value, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeLessThan(String value) {
			addCriterion("material_code <", value, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeLessThanOrEqualTo(String value) {
			addCriterion("material_code <=", value, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeLike(String value) {
			addCriterion("material_code like", value, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeNotLike(String value) {
			addCriterion("material_code not like", value, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeIn(List<String> values) {
			addCriterion("material_code in", values, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeNotIn(List<String> values) {
			addCriterion("material_code not in", values, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeBetween(String value1, String value2) {
			addCriterion("material_code between", value1, value2, "materialCode");
			return (Criteria) this;
		}

		public Criteria andMaterialCodeNotBetween(String value1, String value2) {
			addCriterion("material_code not between", value1, value2, "materialCode");
			return (Criteria) this;
		}

		public Criteria andImageUrlIsNull() {
			addCriterion("image_url is null");
			return (Criteria) this;
		}

		public Criteria andImageUrlIsNotNull() {
			addCriterion("image_url is not null");
			return (Criteria) this;
		}

		public Criteria andImageUrlEqualTo(String value) {
			addCriterion("image_url =", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotEqualTo(String value) {
			addCriterion("image_url <>", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlGreaterThan(String value) {
			addCriterion("image_url >", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlGreaterThanOrEqualTo(String value) {
			addCriterion("image_url >=", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlLessThan(String value) {
			addCriterion("image_url <", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlLessThanOrEqualTo(String value) {
			addCriterion("image_url <=", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlLike(String value) {
			addCriterion("image_url like", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotLike(String value) {
			addCriterion("image_url not like", value, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlIn(List<String> values) {
			addCriterion("image_url in", values, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotIn(List<String> values) {
			addCriterion("image_url not in", values, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlBetween(String value1, String value2) {
			addCriterion("image_url between", value1, value2, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andImageUrlNotBetween(String value1, String value2) {
			addCriterion("image_url not between", value1, value2, "imageUrl");
			return (Criteria) this;
		}

		public Criteria andCompositionIsNull() {
			addCriterion("composition is null");
			return (Criteria) this;
		}

		public Criteria andCompositionIsNotNull() {
			addCriterion("composition is not null");
			return (Criteria) this;
		}

		public Criteria andCompositionEqualTo(String value) {
			addCriterion("composition =", value, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionNotEqualTo(String value) {
			addCriterion("composition <>", value, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionGreaterThan(String value) {
			addCriterion("composition >", value, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionGreaterThanOrEqualTo(String value) {
			addCriterion("composition >=", value, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionLessThan(String value) {
			addCriterion("composition <", value, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionLessThanOrEqualTo(String value) {
			addCriterion("composition <=", value, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionLike(String value) {
			addCriterion("composition like", value, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionNotLike(String value) {
			addCriterion("composition not like", value, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionIn(List<String> values) {
			addCriterion("composition in", values, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionNotIn(List<String> values) {
			addCriterion("composition not in", values, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionBetween(String value1, String value2) {
			addCriterion("composition between", value1, value2, "composition");
			return (Criteria) this;
		}

		public Criteria andCompositionNotBetween(String value1, String value2) {
			addCriterion("composition not between", value1, value2, "composition");
			return (Criteria) this;
		}

		public Criteria andLiningIsNull() {
			addCriterion("lining is null");
			return (Criteria) this;
		}

		public Criteria andLiningIsNotNull() {
			addCriterion("lining is not null");
			return (Criteria) this;
		}

		public Criteria andLiningEqualTo(String value) {
			addCriterion("lining =", value, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningNotEqualTo(String value) {
			addCriterion("lining <>", value, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningGreaterThan(String value) {
			addCriterion("lining >", value, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningGreaterThanOrEqualTo(String value) {
			addCriterion("lining >=", value, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningLessThan(String value) {
			addCriterion("lining <", value, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningLessThanOrEqualTo(String value) {
			addCriterion("lining <=", value, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningLike(String value) {
			addCriterion("lining like", value, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningNotLike(String value) {
			addCriterion("lining not like", value, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningIn(List<String> values) {
			addCriterion("lining in", values, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningNotIn(List<String> values) {
			addCriterion("lining not in", values, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningBetween(String value1, String value2) {
			addCriterion("lining between", value1, value2, "lining");
			return (Criteria) this;
		}

		public Criteria andLiningNotBetween(String value1, String value2) {
			addCriterion("lining not between", value1, value2, "lining");
			return (Criteria) this;
		}

		public Criteria andTidyingIsNull() {
			addCriterion("tidying is null");
			return (Criteria) this;
		}

		public Criteria andTidyingIsNotNull() {
			addCriterion("tidying is not null");
			return (Criteria) this;
		}

		public Criteria andTidyingEqualTo(String value) {
			addCriterion("tidying =", value, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingNotEqualTo(String value) {
			addCriterion("tidying <>", value, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingGreaterThan(String value) {
			addCriterion("tidying >", value, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingGreaterThanOrEqualTo(String value) {
			addCriterion("tidying >=", value, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingLessThan(String value) {
			addCriterion("tidying <", value, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingLessThanOrEqualTo(String value) {
			addCriterion("tidying <=", value, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingLike(String value) {
			addCriterion("tidying like", value, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingNotLike(String value) {
			addCriterion("tidying not like", value, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingIn(List<String> values) {
			addCriterion("tidying in", values, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingNotIn(List<String> values) {
			addCriterion("tidying not in", values, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingBetween(String value1, String value2) {
			addCriterion("tidying between", value1, value2, "tidying");
			return (Criteria) this;
		}

		public Criteria andTidyingNotBetween(String value1, String value2) {
			addCriterion("tidying not between", value1, value2, "tidying");
			return (Criteria) this;
		}

		public Criteria andQianTiaoIsNull() {
			addCriterion("qian_tiao is null");
			return (Criteria) this;
		}

		public Criteria andQianTiaoIsNotNull() {
			addCriterion("qian_tiao is not null");
			return (Criteria) this;
		}

		public Criteria andQianTiaoEqualTo(String value) {
			addCriterion("qian_tiao =", value, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoNotEqualTo(String value) {
			addCriterion("qian_tiao <>", value, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoGreaterThan(String value) {
			addCriterion("qian_tiao >", value, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoGreaterThanOrEqualTo(String value) {
			addCriterion("qian_tiao >=", value, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoLessThan(String value) {
			addCriterion("qian_tiao <", value, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoLessThanOrEqualTo(String value) {
			addCriterion("qian_tiao <=", value, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoLike(String value) {
			addCriterion("qian_tiao like", value, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoNotLike(String value) {
			addCriterion("qian_tiao not like", value, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoIn(List<String> values) {
			addCriterion("qian_tiao in", values, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoNotIn(List<String> values) {
			addCriterion("qian_tiao not in", values, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoBetween(String value1, String value2) {
			addCriterion("qian_tiao between", value1, value2, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andQianTiaoNotBetween(String value1, String value2) {
			addCriterion("qian_tiao not between", value1, value2, "qianTiao");
			return (Criteria) this;
		}

		public Criteria andColorIsNull() {
			addCriterion("color is null");
			return (Criteria) this;
		}

		public Criteria andColorIsNotNull() {
			addCriterion("color is not null");
			return (Criteria) this;
		}

		public Criteria andColorEqualTo(String value) {
			addCriterion("color =", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotEqualTo(String value) {
			addCriterion("color <>", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorGreaterThan(String value) {
			addCriterion("color >", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorGreaterThanOrEqualTo(String value) {
			addCriterion("color >=", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLessThan(String value) {
			addCriterion("color <", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLessThanOrEqualTo(String value) {
			addCriterion("color <=", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorLike(String value) {
			addCriterion("color like", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotLike(String value) {
			addCriterion("color not like", value, "color");
			return (Criteria) this;
		}

		public Criteria andColorIn(List<String> values) {
			addCriterion("color in", values, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotIn(List<String> values) {
			addCriterion("color not in", values, "color");
			return (Criteria) this;
		}

		public Criteria andColorBetween(String value1, String value2) {
			addCriterion("color between", value1, value2, "color");
			return (Criteria) this;
		}

		public Criteria andColorNotBetween(String value1, String value2) {
			addCriterion("color not between", value1, value2, "color");
			return (Criteria) this;
		}

		public Criteria andExtendInfoIsNull() {
			addCriterion("extend_info is null");
			return (Criteria) this;
		}

		public Criteria andExtendInfoIsNotNull() {
			addCriterion("extend_info is not null");
			return (Criteria) this;
		}

		public Criteria andExtendInfoEqualTo(String value) {
			addCriterion("extend_info =", value, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoNotEqualTo(String value) {
			addCriterion("extend_info <>", value, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoGreaterThan(String value) {
			addCriterion("extend_info >", value, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoGreaterThanOrEqualTo(String value) {
			addCriterion("extend_info >=", value, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoLessThan(String value) {
			addCriterion("extend_info <", value, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoLessThanOrEqualTo(String value) {
			addCriterion("extend_info <=", value, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoLike(String value) {
			addCriterion("extend_info like", value, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoNotLike(String value) {
			addCriterion("extend_info not like", value, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoIn(List<String> values) {
			addCriterion("extend_info in", values, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoNotIn(List<String> values) {
			addCriterion("extend_info not in", values, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoBetween(String value1, String value2) {
			addCriterion("extend_info between", value1, value2, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andExtendInfoNotBetween(String value1, String value2) {
			addCriterion("extend_info not between", value1, value2, "extendInfo");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNull() {
			addCriterion("create_time is null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIsNotNull() {
			addCriterion("create_time is not null");
			return (Criteria) this;
		}

		public Criteria andCreateTimeEqualTo(Date value) {
			addCriterion("create_time =", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotEqualTo(Date value) {
			addCriterion("create_time <>", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThan(Date value) {
			addCriterion("create_time >", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("create_time >=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThan(Date value) {
			addCriterion("create_time <", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
			addCriterion("create_time <=", value, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeIn(List<Date> values) {
			addCriterion("create_time in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotIn(List<Date> values) {
			addCriterion("create_time not in", values, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeBetween(Date value1, Date value2) {
			addCriterion("create_time between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
			addCriterion("create_time not between", value1, value2, "createTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNull() {
			addCriterion("update_time is null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIsNotNull() {
			addCriterion("update_time is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeEqualTo(Date value) {
			addCriterion("update_time =", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotEqualTo(Date value) {
			addCriterion("update_time <>", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThan(Date value) {
			addCriterion("update_time >", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("update_time >=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThan(Date value) {
			addCriterion("update_time <", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
			addCriterion("update_time <=", value, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeIn(List<Date> values) {
			addCriterion("update_time in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotIn(List<Date> values) {
			addCriterion("update_time not in", values, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeBetween(Date value1, Date value2) {
			addCriterion("update_time between", value1, value2, "updateTime");
			return (Criteria) this;
		}

		public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
			addCriterion("update_time not between", value1, value2, "updateTime");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table cmt_fabric
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cmt_fabric
     *
     * @mbg.generated do_not_delete_during_merge Mon Jan 08 12:09:24 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}