package com.ifeng.entitys;

import java.util.Date;

public class CtmProduct {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.id
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.name
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.brand_name
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String brandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.status
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private Integer status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.image_url
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String imageUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.sub_images
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String subImages;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.detail_image
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String detailImage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.ad_image
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String adImage;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.vip_price
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private Integer vipPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.market_price
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private Integer marketPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.sub_title
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String subTitle;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.category
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.ctm_props
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private String ctmProps;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.fabric_id
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private Long fabricId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.create_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column ctm_product.update_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.id
	 * @return  the value of ctm_product.id
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.id
	 * @param id  the value for ctm_product.id
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.name
	 * @return  the value of ctm_product.name
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.name
	 * @param name  the value for ctm_product.name
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.brand_name
	 * @return  the value of ctm_product.brand_name
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.brand_name
	 * @param brandName  the value for ctm_product.brand_name
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.status
	 * @return  the value of ctm_product.status
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Integer getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.status
	 * @param status  the value for ctm_product.status
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setStatus(Integer status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.image_url
	 * @return  the value of ctm_product.image_url
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getImageUrl() {
		return imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.image_url
	 * @param imageUrl  the value for ctm_product.image_url
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setImageUrl(String imageUrl) {
		this.imageUrl = imageUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.sub_images
	 * @return  the value of ctm_product.sub_images
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getSubImages() {
		return subImages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.sub_images
	 * @param subImages  the value for ctm_product.sub_images
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setSubImages(String subImages) {
		this.subImages = subImages;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.detail_image
	 * @return  the value of ctm_product.detail_image
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getDetailImage() {
		return detailImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.detail_image
	 * @param detailImage  the value for ctm_product.detail_image
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setDetailImage(String detailImage) {
		this.detailImage = detailImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.ad_image
	 * @return  the value of ctm_product.ad_image
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getAdImage() {
		return adImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.ad_image
	 * @param adImage  the value for ctm_product.ad_image
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setAdImage(String adImage) {
		this.adImage = adImage;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.vip_price
	 * @return  the value of ctm_product.vip_price
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Integer getVipPrice() {
		return vipPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.vip_price
	 * @param vipPrice  the value for ctm_product.vip_price
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setVipPrice(Integer vipPrice) {
		this.vipPrice = vipPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.market_price
	 * @return  the value of ctm_product.market_price
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Integer getMarketPrice() {
		return marketPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.market_price
	 * @param marketPrice  the value for ctm_product.market_price
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setMarketPrice(Integer marketPrice) {
		this.marketPrice = marketPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.sub_title
	 * @return  the value of ctm_product.sub_title
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getSubTitle() {
		return subTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.sub_title
	 * @param subTitle  the value for ctm_product.sub_title
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.category
	 * @return  the value of ctm_product.category
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.category
	 * @param category  the value for ctm_product.category
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setCategory(String category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.ctm_props
	 * @return  the value of ctm_product.ctm_props
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public String getCtmProps() {
		return ctmProps;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.ctm_props
	 * @param ctmProps  the value for ctm_product.ctm_props
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setCtmProps(String ctmProps) {
		this.ctmProps = ctmProps;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.fabric_id
	 * @return  the value of ctm_product.fabric_id
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Long getFabricId() {
		return fabricId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.fabric_id
	 * @param fabricId  the value for ctm_product.fabric_id
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setFabricId(Long fabricId) {
		this.fabricId = fabricId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.create_time
	 * @return  the value of ctm_product.create_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.create_time
	 * @param createTime  the value for ctm_product.create_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column ctm_product.update_time
	 * @return  the value of ctm_product.update_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column ctm_product.update_time
	 * @param updateTime  the value for ctm_product.update_time
	 * @mbg.generated  Mon Jan 08 13:01:10 CST 2018
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}